[package]
name = "basic_prototype_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
sha3 = "0.10.5"
base16ct = {version = "0.1", features = ["alloc"]}